[common]
bin_name = "${BIN_NAME}"
dist_dir = "dist"
checksum_algorithm = "sha256"
staging_dir_template = "{bin_name}_{platform}_{arch}"
artefacts = [
  { source = "target/{target}/release/{bin_name}", required = true, output = "binary_path" },
  { source = "target/generated-man/{target}/release/{bin_name}.1", required = false, output = "man_path", alternatives = ["target/{target}/release/build/*/out/{bin_name}.1"] },
  { source = "LICENSE", required = true, output = "license_path" },
]

[targets.linux-x86_64]
platform = "linux"
arch = "amd64"
target = "x86_64-unknown-linux-gnu"

[targets.linux-aarch64]
platform = "linux"
arch = "arm64"
target = "aarch64-unknown-linux-gnu"

[targets.macos-x86_64]
platform = "macos"
arch = "x86_64"
target = "x86_64-apple-darwin"

[targets.macos-aarch64]
platform = "macos"
arch = "arm64"
target = "aarch64-apple-darwin"

[targets.freebsd-x86_64]
platform = "freebsd"
arch = "amd64"
target = "x86_64-unknown-freebsd"
